# This file was generated by the {rix} R package v0.18.1 on 2026-02-06
# with following call:
# >rix(r_ver = "4.5.1",
#  > r_pkgs = c("magrittr",
#  > "commonmark",
#  > "xml2",
#  > "tibble",
#  > "purrr",
#  > "bslib",
#  > "shiny",
#  > "shinythemes",
#  > "stringr",
#  > "httr",
#  > "clipr",
#  > "fs",
#  > "devtools"),
#  > system_pkgs = c("curl"),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE)
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-10-27.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      bslib
      clipr
      commonmark
      devtools
      fs
      httr
      magrittr
      purrr
      shiny
      shinythemes
      stringr
      tibble
      xml2;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      curl
      glibcLocales
      nix
      R;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
